title : I'm Crhan
tagline: Blog Tagline
author :
  name : Crhan
  email : crhan123@gmail.com
  github : crhan
  twitter : ruohanc
  feedburner : ImCrhan

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md


plugins:
  sitemap_generator:
    file_name: sitemap.xml
    exclude_id:
      - search.html
      - pages.html
    change_frequency_custom_name: changefreq
    priority_custom_variable_name: priority
  google_site_verification: googlef056ebc4b89ca27a
